# sample makefile
all:mybusybox.c
	gcc mybusybox.c -o mybusybox
	ln -s ./mybusybox ./cp
	ln -s ./mybusybox ./ls
	ln -s ./mybusybox ./cat
	ln -s ./mybusybox ./chown

clean:
	rm mybusybox
	rm cp
	rm ls
	rm cat
	rm chown

